version: '3.9'
services:
  mongodb:
    image: "mongo"
    ports:
      - 27017:27017
    env_file:
      - ./.database.env

  service:
    build: .
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - mongodb
